### ISSUE TITLE
Upgrade changes

### ISSUE THREAD

**Issue by AmandaUCSC** [UCSCLibrary/HistoryLog#21]
Hi, I recently updated the History Log plugin from version 1 to version 2, but it seems like the logs can no longer be viewed for individual items? As in, the information used to display below the item (on the admin side obviously) and now you have to go search for it in the History Logs. … Also, I’m unable to find the History Log info for a particular item now. When I go to History Logs and choose “Advanced Reports” I enter an item number but it still returns ALL items when I choose “Report.” Not sure if I’m looking in the wrong place or doing something wrong?

**Comment by NedHenry** [comment]
Thanks for reaching out about this. It has been a long time since we have
done much development on this plugin, and I honestly don't remember whether
this is expected behavior or a bug. It will require some review to figure
out what is going on. Unfortunately, I also need to be realistic about the
fact that we are a bit swamped with other projects, and it may take some
time before we have a chance to address this. If you anyone else in the
omeka community with coding skills has time to take a look in the mean
time, we would welcome the help.

Thanks!

Ned Henry

**Comment by Daniel-KM** [comment]
In the last version, there is an option in the config of the plugin to display the history where you want.

**Comment by NedHenry** [comment]
Thanks Daniel!

**Comment by AmandaUCSC** [comment]
Thanks Daniel - of course it would be so easy as that (if only everything was). I didn't realize it had a configuration page at all!
